controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

funciones:
    resource:
        path: ../src/Funciones/
        namespace: App\Funciones
    type: attribute
